#pragma once

enum AA_PITCH {
	AA_PITCH_OFF,
	AA_PITCH_DYNAMIC,
	AA_PITCH_DOWN,
	AA_PITCH_STRAIGHT,
	AA_PITCH_UP,
};

enum AA_YAW {
	AA_YAW_OFF,
	AA_YAW_BACKWARD,
	AA_YAW_JITTER,
	AA_YAW_INVADE_JITTER,
	AA_YAW_RANDOM_JITTER,
	AA_YAW_SYNCHRONIZE,
	AA_YAW_SPIN,
	AA_YAW_FASTSPIN,
	AA_YAW_MANUAL
};

enum AA_FAKEYAW {
	AA_FAKEYAW_OFF,
	AA_FAKEYAW_FORWARD,
	AA_FAKEYAW_JITTER,
	AA_FAKEYAW_EVADE,
	AA_FAKEYAW_SYNCHRONIZE,
	AA_FAKEYAW_SPIN,
	AA_FAKEYAW_FASTSPIN
};

enum AA_DYNAMICYAW {
	AA_DYNAMICYAW_OFF,
	AA_DYNAMICYAW_FORWARD,
	AA_DYNAMICYAW_EVADE,
	AA_DYNAMICYAW_STATICEVADE,
	AA_DYNAMICYAW_DYNAMICEVADE
};

#define Antiaim CAntiAim::GetInstance()

class CAntiAim {
	IMPLEMENT_SINGLETON(CAntiAim);

public:
	void Run();
private:
	float GetPitch();
	float GetYaw(float pos);
	float GetFakeYaw(float pos);
	float GetDynamicYaw(float pos);
};